/*FONCTION LOGIQUE DE PROGRAMME_ LOGIC PROGRAM FUNCTIONS ___ PROTOTYPES*/
#ifndef __UTIL_CHAINE_H_
#define __UTIL_CHAINE_H_

/*INCLUSION*/
#include "INC_standard.h"


char* LIRECHAINEFORMAT(char *chaine);           //LECTURE D'UNE CHAINE DE CARACTERE FORMATTE_ FORMATTED STRING READING

int LONGUEURFICHIER(FILE* fichier);             //CALCUL DE LA LONGUEUR DU FICHIER_ FILE LENGTH CALCULATION

char LIRECARACTERE();                           //LECTURE D'UN CARACTERE_ CHARACTER READING

char* IMPORTCHAINE();                           //IMPORTATION DE MOT A DEVINER_ WORD TO BE GUESSED IMPORTATION

char* INITIALISER(int taille);                  //INITIALISATION D'UNE CHAINE DE CARACTERE AVEC '*'_ STRING INITIALIZATION WITH '*' CHARACTER

int VERIFICATION(char *chaine, char caractere, char* chaineInter, int *carTrouve);      //VERIFICATION DE L'APPARTENANCE D'UN CARACTERE A UNE CHAINE DE CARACTERE_
                                                                                        //VERIFICATION OF A CHARACTER APPEARENCE INTO A STRING

#endif // __UTIL_CHAINE_H_
