/*FONCTION D'INFORMATION SUR PROGRAMME_ PROGRAM INFORMATIONS FUNCTIONS ___ PROTOTYPES*/
#ifndef __UTIL_PROG_
#define __UTIL_PROG_

/*INCLUSION*/
#include "INC_standard.h"           //INCLUSION BIBLIOTHEQUES STANDARD_ STANDARD LIBS INCLUSION


void INFOPROGEXT(int *fargc, char*** fargv);            //INFORMATIONS DU PROGRAMME EXTERIEURES_ EXTERNAL PROGRAM INFORMATIONS

void INFOPROGINT(void);                                 //INFORMATIONS DU PROGRAMME INTERIEURES_ INTERNAL PROGRAM INFORMATION

void REGLES(void);                                      //EXPLICATION DES REGLES_ RULES EXPLANATION

#endif // __UTIL_PROG_
